import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const helvetica = localFont({
    src: [
        {
            path: '../../public/fonts/helvetica/Helvetica.woff2',
            weight: '400',
            style: 'normal',
        },
    ],
    variable: "--font-helvetica",
})
const helveticaNeue = localFont({
    src: [
        {
            path: '../../public/fonts/helvetica-neue/HelveticaNeueCyr-Light.woff2',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../../public/fonts/helvetica-neue/HelveticaNeueCyr-Medium.woff2',
            weight: '500',
            style: 'normal',
        },
        {
            path: '../../public/fonts/helvetica-neue/HelveticaNeueCyr-MediumItalic.woff2',
            weight: '500',
            style: 'italic',
        },
    ],
    variable: "--font-helvetica-neue",
})
const helveticaNowDisplay = localFont({
    src: [
        {
            path: '../../public/fonts/helvetica-now/HelveticaNowDisplay-Bold.woff2',
            weight: '700',
            style: 'normal',
        },
        {
            path: '../../public/fonts/helvetica-now/HelveticaNowDisplay-Medium.woff2',
            weight: '500',
            style: 'normal',
        },
    ],
    variable: "--font-helvetica-now-display",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${interSans.variable} 
        ${helvetica.variable} 
        ${helveticaNeue.variable} 
        ${helveticaNowDisplay.variable} 
        
        antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
